# Generated by Django 4.2.7 on 2026-05-19 14:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('description', models.TextField()),
                ('thumbnail_url', models.URLField(blank=True, help_text='Optional URL to a thumbnail image for the session.', null=True)),
                ('meeting_link', models.URLField(blank=True, help_text='Optional online meeting link (e.g. Zoom, Google Meet).', null=True)),
                ('price', models.DecimalField(decimal_places=2, help_text='Cost of the session in USD (or local currency).', max_digits=10)),
                ('duration_minutes', models.PositiveIntegerField(help_text='Duration of the session in minutes.')),
                ('max_participants', models.PositiveIntegerField(default=1, help_text='Maximum number of attendees allowed in this session.')),
                ('is_published', models.BooleanField(db_index=True, default=False, help_text='Whether this session is publicly visible.')),
                ('tags', models.CharField(blank=True, help_text='Comma-separated tags for this session.', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(help_text='The creator offering this session.', on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
