# Generated by Django 4.2.7 on 2026-05-20 04:09

from django.db import migrations, models


def set_existing_users_completed(apps, schema_editor):
    User = apps.get_model('users', 'User')
    User.objects.all().update(has_completed_onboarding=True)

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_completed_onboarding',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(set_existing_users_completed, reverse_code=migrations.RunPython.noop),
    ]
